[package]
name = "svgbob-wasm"
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
svgbob = "0.7.2"
wasm-bindgen = "0.2.92"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"